import Foundation
import SwiftUI

enum AppLanguage: String, CaseIterable {
    case system, de, en

    var displayKey: String {
        switch self {
        case .system: return "lang.system"
        case .de:     return "lang.german"
        case .en:     return "lang.english"
        }
    }
}

enum L10n {
    static func resolved(_ stored: String) -> String {
        if stored == "de" || stored == "en" { return stored }
        let pref = Locale.preferredLanguages.first ?? "en"
        return pref.lowercased().hasPrefix("de") ? "de" : "en"
    }

    static func t(_ key: String, _ stored: String) -> String {
        let lang = resolved(stored)
        return strings[lang]?[key] ?? strings["en"]?[key] ?? key
    }

    static func locale(_ stored: String) -> Locale {
        Locale(identifier: resolved(stored))
    }
}

private let strings: [String: [String: String]] = [
    "de": [
        // Top bar / navigation
        "nav.today": "Heute",
        "nav.menu": "Menü",
        "nav.done": "Fertig",

        // View types
        "view.month": "Monat",
        "view.week": "Woche",
        "view.day": "Tag",
        "view.quarter": "Quartal",
        "view.agenda": "Termine",
        "view.change": "Ansicht",

        // Calendar misc
        "cal.cw": "KW",
        "cal.allday": "Ganztägig",
        "cal.no_events_title": "Keine Termine",
        "cal.no_events_body": "In den nächsten 90 Tagen sind keine Termine vorhanden.",
        "cal.loading_more": "Lade weitere Wochen…",
        "cal.new_event": "Neues Ereignis",
        "cal.show_in_day_view": "In Tagesansicht öffnen",
        "cal.show_in_week_view": "In Wochenansicht öffnen",
        "cal.show_in_month_view": "In Monatsansicht öffnen",

        // Menu sheet
        "menu.section.settings": "Einstellungen",
        "menu.profile": "Profil",
        "menu.appearance": "Darstellung",
        "menu.accounts": "Konten & Kalender",
        "menu.server": "Server",
        "menu.logout": "Abmelden",
        "menu.admin": "Admin",
        "menu.sync": "Mit Server synchronisieren",
        "menu.sync.section": "Synchronisierung",

        // Settings – chrome
        "settings.title": "Darstellung",
        "settings.loading": "Lade Einstellungen…",
        "settings.save": "Speichern",
        "settings.saved": "Gespeichert",

        // Settings – sections
        "settings.appdesign": "App-Design",
        "settings.liquidglass": "Liquid Glass",
        "settings.liquidglass.desc": "Verwendet die neue iOS\u{202F}26 Glasoptik mit transparenter Navigationsleiste",
        "settings.liquidglass.footer": "Änderung wirkt sofort – kein Neustart nötig.",
        "settings.sync": "Einstellungen synchronisieren",
        "settings.sync.desc": "Darstellung mit dem Server abgleichen",
        "settings.sync.footer": "Wenn aktiv, werden Farben, Kontraste und Stundenhöhe mit dem Server abgeglichen (der Server hat Vorrang). Ansicht, erster Wochentag und das Ausgrauen vergangener Termine werden immer synchronisiert – auch wenn der Schalter aus ist.",
        "settings.sync_all": "Alle synchronisieren",
        "settings.sync_all.desc": "Diese Einstellungen zwischen deinen Geräten teilen",
        "settings.sync_this": "Zwischen Geräten synchronisieren",
        "settings.reset": "Zurücksetzen",
        "settings.appearance": "Ansicht",
        "settings.color.surface": "Topbar-/Oberflächenfarbe",
        "settings.surface.auto": "Auto (Milchglas)",
        "settings.device": "Nur auf diesem Gerät",
        "settings.hide_menu_button": "Menü-Button ausblenden",
        "settings.device.footer": "Diese Einstellungen gelten nur auf diesem Gerät und werden nicht synchronisiert.",

        "settings.cache.header": "Vorladen",
        "settings.cache.title": "Vorladen",
        "settings.cache.desc": "Events werden beim Start im Hintergrund für diesen Zeitraum geladen, danach ist Wischen sofort.",
        "settings.cache.range": "Zeitraum",
        "settings.cache.1m": "±1 Monat",
        "settings.cache.3m": "±3 Monate",
        "settings.cache.6m": "±6 Monate",
        "settings.cache.1y": "±1 Jahr",
        "settings.cache.footer": "Mehr Monate = längerer initialer Ladevorgang, danach komplett ohne Wartezeiten navigierbar.",

        "settings.language": "Sprache",
        "lang.system": "Systemstandard",
        "lang.german": "Deutsch",
        "lang.english": "English",

        "settings.colors": "Farben",
        "settings.color.primary": "Primärfarbe",
        "settings.color.accent": "Akzentfarbe",
        "settings.color.today": "Heutige-Tag-Farbe",
        "settings.color.divider": "Monatswechsel-Linie",
        "settings.color.label": "Monatskürzel",
        "settings.color.text": "Schriftfarbe",
        "settings.color.background": "Hintergrundfarbe",
        "settings.color.line": "Linienfarbe",

        "settings.textcontrast": "Schriftkontrast",
        "settings.textcontrast.desc": "Helligkeit der Beschriftungen und Texte",
        "settings.contrast.dark": "Dunkel",
        "settings.contrast.medium": "Mittel",
        "settings.contrast.bright": "Hell",
        "settings.contrast.max": "Maximum",

        "settings.linecontrast": "Linienkontrast",
        "settings.linecontrast.desc": "Sichtbarkeit von Trennlinien und Rahmen",
        "settings.linecontrast.barely": "Kaum",
        "settings.linecontrast.subtle": "Subtil",
        "settings.linecontrast.normal": "Normal",
        "settings.linecontrast.strong": "Stark",

        "settings.calview": "Kalenderansicht",
        "settings.defaultview": "Standardansicht",
        "settings.firstweekday": "Erster Wochentag",
        "settings.monday": "Montag",
        "settings.sunday": "Sonntag",
        "settings.dimpast": "Vergangene Termine ausgrauen",
        "settings.month_paged": "Monatsansicht seitenweise wischen",
        "settings.month_mode": "Monatswechsel",
        "settings.month_mode.scroll": "Fortlaufend scrollen",
        "settings.month_mode.paged": "Seitenweise blättern",
        "settings.default_duration": "Standard-Termindauer",
        "settings.nav.profile": "Profil",
        "settings.privacy": "Privatsphäre",
        "settings.private_visibility": "Private Termine für Gruppen",
        "settings.private_visibility.desc": "Wie private Termine für andere Gruppenmitglieder erscheinen",
        "settings.directory_hidden": "Profil verbergen",
        "settings.directory_hidden.desc": "Nicht in Teilen-/Gruppen-Auswahl anzeigen. In der Admin-Benutzerverwaltung bleibst du sichtbar.",
        "settings.private.busy": "Als „Beschäftigt“",
        "settings.private.hidden": "Ausblenden",
        "settings.calendars": "Geteilter Kalender",
        "settings.group_visible": "Für Gruppen sichtbar",
        "settings.group_visible.desc": "Wähle, welcher deiner Kalender für Gruppenmitglieder sichtbar ist",
        "group.visible.none": "Keiner",
        "profile.display_name": "Anzeigename",
        "profile.login_name": "Login-Name",
        "accounts.shared_by": "geteilt von %@",
        "share.title": "Teilen",
        "share.current": "Aktuelle Freigaben",
        "share.none": "Noch nicht geteilt",
        "share.add": "Benutzer hinzufügen",
        "share.search": "Benutzer suchen…",
        "share.permission": "Berechtigung",
        "perm.read": "Nur lesen",
        "perm.read_write": "Lesen & schreiben",
        "ics.import": "Importieren",
        "ics.export": "Exportieren",
        "ics.import_result": "%d importiert, %d übersprungen",
        "common.info": "Info",
        "common.done": "Fertig",
        "groups.title": "Gruppen",
        "groups.personal": "Persönlich",
        "groups.view_label": "Gruppenansicht",
        "groups.exit": "Verlassen",
        "groups.none": "Noch keine Gruppen",
        "groups.combined_empty": "Keine Termine in diesem Zeitraum",
        "group.create": "Gruppe erstellen",
        "group.manage": "Gruppe verwalten",
        "group.name": "Name",
        "group.icon": "Icon",
        "group.members": "Mitglieder",
        "group.calendar": "Gruppenkalender",
        "group.member_colors": "Farben der Mitglieder",
        "group.delete": "Gruppe löschen",

        "settings.hourheight": "Stundenhöhe",
        "settings.hourheight.desc": "Platz pro Stunde in der Wochen- & Tagesansicht",
        "settings.hourheight.compact": "Kompakt",
        "settings.hourheight.normal": "Normal",
        "settings.hourheight.comfort": "Komfort",
        "settings.hourheight.large": "Gross",

        // Common buttons
        "common.cancel": "Abbrechen",
        "common.close": "Schliessen",
        "common.ok": "OK",
        "common.error": "Fehler",

        // Server view
        "server.title": "Server",
        "server.connected": "Verbundener Server",
        "server.switch": "Server wechseln",
        "server.switch_msg": "Verbindung zu %@ wird getrennt und alle lokalen Anmeldedaten werden gelöscht.",
        "server.logout_title": "Abmelden",
        "server.logout_msg": "Du wirst von %@ abgemeldet.",
        "server.info": "Info",
        "server.imprint": "Impressum",
        "server.version": "Version",

        // Imprint
        "imprint.company": "Scarriffleservices",
        "imprint.role": "Software & Webentwicklung",
        "imprint.copyright": "Diese Software wurde von Scarriffleservices mit grösster Sorgfalt entwickelt und bereitgestellt. Alle Rechte vorbehalten © 2026 Scarriffleservices.",
        "imprint.storage.title": "Datenspeicherung",
        "imprint.storage.body": "Alle Anwendungsdaten werden auf dem Server gespeichert und verarbeitet, auf dem diese Calendarr-Instanz betrieben wird. Der Speicherort hängt damit vom Betreiber des jeweiligen Servers ab. Bei Nutzung der Google Kalender-Anbindung werden Daten über die Google API ausgetauscht; für diese Daten gelten die Datenschutzbestimmungen von Google. Bei Nutzung der Home Assistant-Anbindung werden Daten mit der jeweiligen Home Assistant-Instanz ausgetauscht. Home Assistant ist ein Projekt der Open Home Foundation.",
        "imprint.disclaimer.title": "Haftungsausschluss",
        "imprint.disclaimer.body": "Trotz sorgfältiger Erstellung wird keine Haftung für die Richtigkeit, Vollständigkeit oder Aktualität der bereitgestellten Inhalte übernommen. Die Nutzung erfolgt auf eigene Verantwortung.",
        "imprint.contact.title": "Kontakt",

        // Profile view
        "profile.title": "Profil",
        "profile.loading": "Lade Profil…",
        "profile.account": "Konto",
        "profile.username": "Benutzername",
        "profile.role": "Rolle",
        "profile.role.admin": "Administrator",
        "profile.role.user": "Benutzer",
        "profile.email": "E-Mail",
        "profile.no_email": "Keine E-Mail",
        "profile.save_email": "E-Mail speichern",
        "profile.email_saved": "E-Mail gespeichert",
        "profile.change_password": "Passwort ändern",
        "profile.current_password": "Aktuelles Passwort",
        "profile.new_password": "Neues Passwort",
        "profile.new_password_repeat": "Neues Passwort wiederholen",
        "profile.password_mismatch": "Passwörter stimmen nicht überein",
        "profile.password_changed": "Passwort geändert",
        "profile.twofa": "Zwei-Faktor-Authentifizierung",
        "profile.twofa.active": "2FA ist aktiviert",
        "profile.twofa.inactive": "2FA ist deaktiviert",
        "profile.twofa.enable": "2FA einrichten",
        "profile.twofa.disable": "2FA deaktivieren",
        "profile.twofa.enabled_toast": "2FA aktiviert",
        "profile.twofa.disabled_toast": "2FA deaktiviert",
        "twofa.setup_title": "2FA einrichten",
        "twofa.scan_hint": "Scanne den QR-Code mit deiner Authenticator-App (z.B. Bitwarden, Google Authenticator).",
        "twofa.qr_section": "QR-Code / Manueller Schlüssel",
        "twofa.confirmation": "Bestätigung",
        "twofa.code_placeholder": "6-stelliger Code",
        "twofa.activate": "Aktivieren",
        "twofa.disable_title": "2FA deaktivieren",
        "twofa.password_section": "Passwort zum Deaktivieren",
        "twofa.password_placeholder": "Passwort",
        "twofa.disable": "Deaktivieren",

        // Event editor
        "event.title_placeholder": "Titel",
        "event.allday": "Ganztägig",
        "event.private": "Privat",
        "event.attachments": "Anhänge",
        "event.attachment_add": "Datei hinzufügen",
        "event.attachment_hint": "Max. 10 MB pro Datei, 10 Dateien. PDF, Bilder, Text.",
        "event.attachment_failed": "Anhänge konnten nicht vollständig gespeichert werden.",
        "event.start": "Start",
        "event.end": "Ende",
        "event.location": "Ort",
        "event.description": "Beschreibung",
        "event.calendar_section": "Kalender",
        "event.no_writable": "Keine beschreibbaren Kalender vorhanden",
        "event.calendar_picker": "Kalender",
        "event.color_section": "Farbe",
        "event.color": "Terminfarbe",
        "event.reset_color": "Zurücksetzen",
        "event.edit_title": "Termin bearbeiten",
        "event.new_title": "Neuer Termin",
        "event.copy_title": "Termin kopieren",
        "event.copy_to": "In Kalender kopieren",
        "event.save": "Sichern",
        "event.add": "Hinzufügen",

        // Event detail
        "detail.title": "Termin",
        "detail.source": "Quelle",
        "detail.created_by": "Erstellt von",
        "detail.delete": "Termin löschen",
        "detail.edit": "Bearbeiten",
        "detail.delete_confirm_title": "Termin löschen?",
        "detail.delete_msg_suffix": "wird dauerhaft gelöscht.",
        "common.delete": "Löschen",

        // Login / server setup
        "login.username": "Benutzername",
        "login.password": "Passwort",
        "login.totp": "2FA-Code",
        "login.totp_placeholder": "6-stelliger Code",
        "login.remember": "Angemeldet bleiben",
        "login.signin": "Anmelden",
        "login.choose_server": "Anderen Server wählen",
        // Single sign-on (OpenID Connect)
        "sso.or": "oder",
        "sso.login_with": "Mit %@ anmelden",
        "sso.err.generic": "Anmeldung fehlgeschlagen",
        "sso.err.oidc_failed": "Anmeldung fehlgeschlagen",
        "sso.err.oidc_provider_unreachable": "Anmeldedienst nicht erreichbar",
        "sso.err.oidc_guided_access": "Bei aktiviertem geführten Zugriff ist die SSO-Anmeldung nicht möglich",
        "sso.err.oidc_refresh_failed": "Sitzung konnte nicht erneuert werden",
        "sso.err.oidc_no_presenter": "Anmeldefenster konnte nicht geöffnet werden",
        "sso.err.oidc_bad_issuer": "Der Anbieter ist falsch konfiguriert",
        "sso.err.oidc_account_not_linked": "Kein verknüpftes Calendarr-Konto. Bitte lokal anmelden und in den Einstellungen verknüpfen.",
        "sso.err.oidc_signup_disabled": "Automatische Kontoerstellung ist deaktiviert",
        "sso.err.oidc_domain_not_allowed": "Diese E-Mail-Domain ist nicht zugelassen",
        "sso.err.oidc_email_conflict": "Diese E-Mail-Adresse gehört bereits zu einem anderen Konto",
        "sso.err.oidc_email_not_verified": "E-Mail-Adresse beim Anbieter nicht bestätigt",
        "sso.err.oidc_no_email": "Der Anbieter hat keine E-Mail-Adresse übermittelt",
        "sso.err.oidc_unknown_client": "Diese App ist beim Anbieter nicht registriert",
        "sso.err.oidc_invalid_token": "Das Anmelde-Token ist ungültig",
        "sso.err.oidc_no_id_token": "Der Anbieter hat kein ID-Token geliefert",
        "server.connect_title": "Server verbinden",
        "server.url": "Server-URL",
        "server.connect": "Verbinden",
        "server.unreachable": "Server nicht erreichbar. URL prüfen.",
        "settings.email": "E-Mail",

        // Accounts
        "accounts.title": "Konten",
        "accounts.loading": "Lade Konten…",
        "accounts.add.caldav": "CalDAV-Konto",
        "accounts.add.local": "Lokaler Kalender",
        "accounts.add.birthday": "Geburtstagskalender",
        "accounts.add.ical": "iCal-URL abonnieren",
        "accounts.add.ha": "Home Assistant",
        "accounts.caldav.header": "CalDAV-Konten",
        "accounts.caldav.empty": "Keine CalDAV-Konten",
        "accounts.caldav.add": "CalDAV hinzufügen",
        "accounts.local.header": "Lokale Kalender",
        "accounts.local.empty": "Keine lokalen Kalender",
        "accounts.local.add": "Lokalen Kalender erstellen",
        "accounts.ical.header": "iCal-Abonnements",
        "accounts.ical.empty": "Keine Abonnements",
        "accounts.ical.every": "Alle %d Min.",
        "accounts.ical.add": "iCal-URL abonnieren",
        "accounts.google.header": "Google-Konten",
        "accounts.google.empty": "Keine Google-Konten",
        "accounts.google.hint": "Google-Konten werden über den Browser verknüpft",
        "accounts.ha.header": "Home Assistant",
        "accounts.ha.empty": "Keine Home Assistant-Konten",
        "accounts.ha.add": "Home Assistant hinzufügen",
        "profile.admin_note": "Hinweis: Die Benutzerverwaltung – sowohl das Erstellen als auch das Löschen von Benutzerkonten – erfolgt ausschließlich durch den Administrator des Servers.",

        // Kalender-Filter (Sidebar)
        "filter.title": "Kalender",
        "filter.loading": "Lade Kalender…",
        "filter.empty": "Keine Kalender vorhanden",
        "filter.show_all": "Alle anzeigen",
        "filter.hide_all": "Alle ausblenden",
        "filter.sort": "Sortieren",
        "filter.done": "Fertig",
        "filter.button": "Kalender ein-/ausblenden",
        "filter.banish": "Dauerhaft ausblenden",
        "filter.reminders_on": "Benachrichtigungen an",
        "filter.reminders_off": "Benachrichtigungen aus",
        "filter.banished_footer": "Dauerhaft ausgeblendete Kalender erscheinen unter »Konten & Kalender« und können dort wieder eingeblendet werden.",
        "accounts.banished_header": "Ausgeblendete Kalender",
        "accounts.banished_unhide": "Wieder einblenden",
        "accounts.banished_unknown": "Unbekannter Kalender",

        // CalDAV add sheet
        "caldav.section": "Konto-Details",
        "caldav.display_name": "Anzeigename",
        "caldav.url": "CalDAV-URL",
        "caldav.username": "Benutzername",
        "caldav.password": "Passwort",
        "caldav.color": "Farbe",
        "caldav.color_label": "Farbe",
        "caldav.color_section": "Farbe",
        "caldav.connect": "Verbinden",
        "caldav.title": "CalDAV-Konto",

        // Local cal add sheet
        "local.title": "Lokaler Kalender",
        "local.name": "Name",
        "local.color": "Farbe",
        "local.create": "Erstellen",

        // Birthdays
        "birthday.new": "Neuer Geburtstag",
        "birthday.calendar_name": "Geburtstage",
        "birthday.activate": "Geburtstagskalender aktivieren",
        "birthday.activate_hint": "Aktiviere den Geburtstagskalender, um Geburtstage anzulegen. Er erscheint als eigener Kalender in der Seitenleiste.",
        "birthday.person": "Name",
        "birthday.person_placeholder": "Name der Person",
        "birthday.date": "Geburtstag",
        "birthday.year_unknown": "Jahr unbekannt",
        "birthday.no_calendars": "Kein Geburtstagskalender vorhanden. Erstelle zuerst einen unter „Konten & Kalender“.",
        "birthday.is_calendar": "Geburtstagskalender",
        "birthday.is_calendar.desc": "Ganztägige, jährliche Termine mit Alter und Geburtstags-Icon.",
        "birthday.notify": "Erinnerung",
        "birthday.notify.off": "Aus",
        "birthday.notify.same_day": "Am Tag",
        "birthday.notify.one_day": "1 Tag vorher",
        "birthday.notify.days": "%d Tage vorher",
        "birthday.contacts.header": "Geburtstage aus Kontakten",
        "birthday.contacts.sync": "Aus Kontakten synchronisieren",
        "birthday.contacts.target": "Zielkalender",
        "birthday.contacts.sync_now": "Jetzt synchronisieren",
        "birthday.contacts.synced": "Geburtstage synchronisiert",
        "birthday.contacts.hint": "Überträgt Geburtstage aus deinen Kontakten in den gewählten Geburtstagskalender – sichtbar auf allen Geräten.",
        "birthday.contacts.denied": "Kein Zugriff auf Kontakte. Bitte in den iOS-Einstellungen erlauben.",
        "birthday.contacts.need_calendar": "Erstelle zuerst einen Geburtstagskalender.",

        // iCal add sheet
        "ical.title": "iCal abonnieren",
        "ical.subscription": "Abonnement",
        "ical.name": "Name",
        "ical.url": "iCal-URL",
        "ical.color": "Farbe",
        "ical.refresh_section": "Aktualisierung",
        "ical.interval": "Intervall",
        "ical.subscribe": "Abonnieren",
        "ical.refresh.15m": "Alle 15 Min.",
        "ical.refresh.30m": "Alle 30 Min.",
        "ical.refresh.1h": "Stündlich",
        "ical.refresh.6h": "Alle 6 Std.",
        "ical.refresh.1d": "Täglich",

        // HA add sheet
        "ha.section": "Home Assistant",
        "ha.display_name": "Anzeigename",
        "ha.url_placeholder": "URL (z.B. http://homeassistant.local:8123)",
        "ha.auth_section": "Authentifizierung",
        "ha.token": "Long-Lived Access Token",
        "ha.token_hint": "Token erstellen unter: Profil → Sicherheit → Long-Lived Access Tokens",
        "ha.connect": "Verbinden"
    ],
    "en": [
        "nav.today": "Today",
        "nav.menu": "Menu",
        "nav.done": "Done",

        "view.month": "Month",
        "view.week": "Week",
        "view.day": "Day",
        "view.quarter": "Quarter",
        "view.agenda": "Agenda",
        "view.change": "View",

        "cal.cw": "W",
        "cal.allday": "All-day",
        "cal.no_events_title": "No events",
        "cal.no_events_body": "No events in the next 90 days.",
        "cal.loading_more": "Loading more weeks…",
        "cal.new_event": "New event",
        "cal.show_in_day_view": "Open in day view",
        "cal.show_in_week_view": "Open in week view",
        "cal.show_in_month_view": "Open in month view",

        "menu.section.settings": "Settings",
        "menu.profile": "Profile",
        "menu.appearance": "Appearance",
        "menu.accounts": "Accounts & Calendars",
        "menu.server": "Server",
        "menu.logout": "Sign out",
        "menu.admin": "Admin",
        "menu.sync": "Sync with server",
        "menu.sync.section": "Synchronization",

        "settings.title": "Appearance",
        "settings.loading": "Loading settings…",
        "settings.save": "Save",
        "settings.saved": "Saved",

        "settings.appdesign": "App design",
        "settings.liquidglass": "Liquid Glass",
        "settings.liquidglass.desc": "Uses the new iOS\u{202F}26 glass look with a translucent navigation bar",
        "settings.liquidglass.footer": "Takes effect immediately – no restart required.",
        "settings.sync": "Sync settings",
        "settings.sync.desc": "Keep appearance in sync with the server",
        "settings.sync.footer": "When on, colors, contrasts and hour height sync with the server (the server wins). View, first weekday and dimming past events always sync – even when the switch is off.",
        "settings.sync_all": "Sync all",
        "settings.sync_all.desc": "Share these settings across your devices",
        "settings.sync_this": "Sync across devices",
        "settings.reset": "Reset",
        "settings.appearance": "View",
        "settings.color.surface": "Top bar / surface color",
        "settings.surface.auto": "Auto (translucent)",
        "settings.device": "This device only",
        "settings.hide_menu_button": "Hide menu button",
        "settings.device.footer": "These settings apply to this device only and are not synced.",

        "settings.cache.header": "Preloading",
        "settings.cache.title": "Preloading",
        "settings.cache.desc": "Events are loaded in the background for this range on launch, so swiping is instant afterwards.",
        "settings.cache.range": "Range",
        "settings.cache.1m": "±1 month",
        "settings.cache.3m": "±3 months",
        "settings.cache.6m": "±6 months",
        "settings.cache.1y": "±1 year",
        "settings.cache.footer": "More months = longer initial load, but then fully wait-free navigation.",

        "settings.language": "Language",
        "lang.system": "System default",
        "lang.german": "Deutsch",
        "lang.english": "English",

        "settings.colors": "Colors",
        "settings.color.primary": "Primary color",
        "settings.color.accent": "Accent color",
        "settings.color.today": "Today color",
        "settings.color.divider": "Month divider line",
        "settings.color.label": "Month abbreviation",
        "settings.color.text": "Text color",
        "settings.color.background": "Background color",
        "settings.color.line": "Line color",

        "settings.textcontrast": "Text contrast",
        "settings.textcontrast.desc": "Brightness of labels and text",
        "settings.contrast.dark": "Dark",
        "settings.contrast.medium": "Medium",
        "settings.contrast.bright": "Bright",
        "settings.contrast.max": "Maximum",

        "settings.linecontrast": "Line contrast",
        "settings.linecontrast.desc": "Visibility of dividers and borders",
        "settings.linecontrast.barely": "Barely",
        "settings.linecontrast.subtle": "Subtle",
        "settings.linecontrast.normal": "Normal",
        "settings.linecontrast.strong": "Strong",

        "settings.calview": "Calendar view",
        "settings.defaultview": "Default view",
        "settings.firstweekday": "First day of week",
        "settings.monday": "Monday",
        "settings.sunday": "Sunday",
        "settings.dimpast": "Dim past events",
        "settings.month_paged": "Swipe month view as pages",
        "settings.month_mode": "Month switching",
        "settings.month_mode.scroll": "Continuous scroll",
        "settings.month_mode.paged": "Page by page",
        "settings.default_duration": "Default event duration",
        "settings.nav.profile": "Profile",
        "settings.privacy": "Privacy",
        "settings.private_visibility": "Private events for groups",
        "settings.private_visibility.desc": "How your private events appear to other group members",
        "settings.directory_hidden": "Hide my profile",
        "settings.directory_hidden.desc": "Don't show me in share/group pickers. You stay visible in the admin user management.",
        "settings.private.busy": "Show as \"Busy\"",
        "settings.private.hidden": "Hide",
        "settings.calendars": "Shared calendar",
        "settings.group_visible": "Visible to groups",
        "settings.group_visible.desc": "Choose which of your calendars group members can see",
        "group.visible.none": "None",
        "profile.display_name": "Display name",
        "profile.login_name": "Login name",
        "accounts.shared_by": "shared by %@",
        "share.title": "Share",
        "share.current": "Current shares",
        "share.none": "Not shared yet",
        "share.add": "Add user",
        "share.search": "Search users…",
        "share.permission": "Permission",
        "perm.read": "Read only",
        "perm.read_write": "Read & write",
        "ics.import": "Import",
        "ics.export": "Export",
        "ics.import_result": "%d imported, %d skipped",
        "common.info": "Info",
        "common.done": "Done",
        "groups.title": "Groups",
        "groups.personal": "Personal",
        "groups.view_label": "Group view",
        "groups.exit": "Exit",
        "groups.none": "No groups yet",
        "groups.combined_empty": "No events in this period",
        "group.create": "Create group",
        "group.manage": "Manage group",
        "group.name": "Name",
        "group.icon": "Icon",
        "group.members": "Members",
        "group.calendar": "Group calendar",
        "group.member_colors": "Member colours",
        "group.delete": "Delete group",

        "settings.hourheight": "Hour height",
        "settings.hourheight.desc": "Space per hour in week & day view",
        "settings.hourheight.compact": "Compact",
        "settings.hourheight.normal": "Normal",
        "settings.hourheight.comfort": "Comfort",
        "settings.hourheight.large": "Large",

        // Common buttons
        "common.cancel": "Cancel",
        "common.close": "Close",
        "common.ok": "OK",
        "common.error": "Error",

        // Server view
        "server.title": "Server",
        "server.connected": "Connected server",
        "server.switch": "Switch server",
        "server.switch_msg": "The connection to %@ will be closed and all local credentials will be removed.",
        "server.logout_title": "Sign out",
        "server.logout_msg": "You will be signed out of %@.",
        "server.info": "Info",
        "server.imprint": "Legal notice",
        "server.version": "Version",

        // Imprint
        "imprint.company": "Scarriffleservices",
        "imprint.role": "Software & web development",
        "imprint.copyright": "This software was carefully developed and provided by Scarriffleservices. All rights reserved © 2026 Scarriffleservices.",
        "imprint.storage.title": "Data storage",
        "imprint.storage.body": "All application data is stored and processed on the server on which this Calendarr instance is hosted. The storage location therefore depends on the operator of the respective server. When using the Google Calendar integration, data is exchanged via the Google API; Google's privacy policy applies to that data. When using the Home Assistant integration, data is exchanged with the respective Home Assistant instance. Home Assistant is a project of the Open Home Foundation.",
        "imprint.disclaimer.title": "Disclaimer",
        "imprint.disclaimer.body": "Despite careful preparation, no liability is assumed for the accuracy, completeness or topicality of the content provided. Use is at your own risk.",
        "imprint.contact.title": "Contact",

        // Profile view
        "profile.title": "Profile",
        "profile.loading": "Loading profile…",
        "profile.account": "Account",
        "profile.username": "Username",
        "profile.role": "Role",
        "profile.role.admin": "Administrator",
        "profile.role.user": "User",
        "profile.email": "Email",
        "profile.no_email": "No email",
        "profile.save_email": "Save email",
        "profile.email_saved": "Email saved",
        "profile.change_password": "Change password",
        "profile.current_password": "Current password",
        "profile.new_password": "New password",
        "profile.new_password_repeat": "Repeat new password",
        "profile.password_mismatch": "Passwords don't match",
        "profile.password_changed": "Password changed",
        "profile.twofa": "Two-factor authentication",
        "profile.twofa.active": "2FA is enabled",
        "profile.twofa.inactive": "2FA is disabled",
        "profile.twofa.enable": "Set up 2FA",
        "profile.twofa.disable": "Disable 2FA",
        "profile.twofa.enabled_toast": "2FA enabled",
        "profile.twofa.disabled_toast": "2FA disabled",
        "twofa.setup_title": "Set up 2FA",
        "twofa.scan_hint": "Scan the QR code with your authenticator app (e.g. Bitwarden, Google Authenticator).",
        "twofa.qr_section": "QR code / Manual key",
        "twofa.confirmation": "Verification",
        "twofa.code_placeholder": "6-digit code",
        "twofa.activate": "Activate",
        "twofa.disable_title": "Disable 2FA",
        "twofa.password_section": "Password to disable",
        "twofa.password_placeholder": "Password",
        "twofa.disable": "Disable",

        // Event editor
        "event.title_placeholder": "Title",
        "event.allday": "All-day",
        "event.private": "Private",
        "event.attachments": "Attachments",
        "event.attachment_add": "Add file",
        "event.attachment_hint": "Max. 10 MB per file, 10 files. PDF, images, text.",
        "event.attachment_failed": "Attachments could not be saved completely.",
        "event.start": "Start",
        "event.end": "End",
        "event.location": "Location",
        "event.description": "Description",
        "event.calendar_section": "Calendar",
        "event.no_writable": "No writable calendars available",
        "event.calendar_picker": "Calendar",
        "event.color_section": "Color",
        "event.color": "Event color",
        "event.reset_color": "Reset",
        "event.edit_title": "Edit event",
        "event.new_title": "New event",
        "event.copy_title": "Copy event",
        "event.copy_to": "Copy to calendar",
        "event.save": "Save",
        "event.add": "Add",

        // Event detail
        "detail.title": "Event",
        "detail.source": "Source",
        "detail.created_by": "Created by",
        "detail.delete": "Delete event",
        "detail.edit": "Edit",
        "detail.delete_confirm_title": "Delete event?",
        "detail.delete_msg_suffix": "will be permanently deleted.",
        "common.delete": "Delete",

        // Login / server setup
        "login.username": "Username",
        "login.password": "Password",
        "login.totp": "2FA code",
        "login.totp_placeholder": "6-digit code",
        "login.remember": "Stay signed in",
        "login.signin": "Sign in",
        "login.choose_server": "Choose another server",
        // Single sign-on (OpenID Connect)
        "sso.or": "or",
        "sso.login_with": "Sign in with %@",
        "sso.err.generic": "Sign-in failed",
        "sso.err.oidc_failed": "Sign-in failed",
        "sso.err.oidc_provider_unreachable": "Sign-in service unreachable",
        "sso.err.oidc_guided_access": "SSO sign-in is not available while Guided Access is on",
        "sso.err.oidc_refresh_failed": "Could not renew the session",
        "sso.err.oidc_no_presenter": "Could not open the sign-in window",
        "sso.err.oidc_bad_issuer": "The provider is misconfigured",
        "sso.err.oidc_account_not_linked": "No linked Calendarr account. Sign in locally and link it in Settings.",
        "sso.err.oidc_signup_disabled": "Automatic account creation is disabled",
        "sso.err.oidc_domain_not_allowed": "This email domain is not allowed",
        "sso.err.oidc_email_conflict": "That email address already belongs to another account",
        "sso.err.oidc_email_not_verified": "Email address not verified at the provider",
        "sso.err.oidc_no_email": "The provider did not supply an email address",
        "sso.err.oidc_unknown_client": "This app is not registered with the provider",
        "sso.err.oidc_invalid_token": "The sign-in token is invalid",
        "sso.err.oidc_no_id_token": "The provider did not return an ID token",
        "server.connect_title": "Connect server",
        "server.url": "Server URL",
        "server.connect": "Connect",
        "server.unreachable": "Server unreachable. Check the URL.",
        "settings.email": "Email",

        // Accounts
        "accounts.title": "Accounts",
        "accounts.loading": "Loading accounts…",
        "accounts.add.caldav": "CalDAV account",
        "accounts.add.local": "Local calendar",
        "accounts.add.birthday": "Birthday calendar",
        "accounts.add.ical": "Subscribe to iCal URL",
        "accounts.add.ha": "Home Assistant",
        "accounts.caldav.header": "CalDAV accounts",
        "accounts.caldav.empty": "No CalDAV accounts",
        "accounts.caldav.add": "Add CalDAV",
        "accounts.local.header": "Local calendars",
        "accounts.local.empty": "No local calendars",
        "accounts.local.add": "Create local calendar",
        "accounts.ical.header": "iCal subscriptions",
        "accounts.ical.empty": "No subscriptions",
        "accounts.ical.every": "Every %d min",
        "accounts.ical.add": "Subscribe to iCal URL",
        "accounts.google.header": "Google accounts",
        "accounts.google.empty": "No Google accounts",
        "accounts.google.hint": "Google accounts are linked via the browser",
        "accounts.ha.header": "Home Assistant",
        "accounts.ha.empty": "No Home Assistant accounts",
        "accounts.ha.add": "Add Home Assistant",
        "profile.admin_note": "Note: User management — both the creation and deletion of user accounts — is handled exclusively by the server administrator.",

        // Calendar filter (sidebar)
        "filter.title": "Calendars",
        "filter.loading": "Loading calendars…",
        "filter.empty": "No calendars available",
        "filter.show_all": "Show all",
        "filter.hide_all": "Hide all",
        "filter.sort": "Sort",
        "filter.done": "Done",
        "filter.button": "Show/hide calendars",
        "filter.banish": "Hide permanently",
        "filter.reminders_on": "Reminders on",
        "filter.reminders_off": "Reminders off",
        "filter.banished_footer": "Permanently hidden calendars appear under “Accounts & Calendars”, where you can show them again.",
        "accounts.banished_header": "Hidden calendars",
        "accounts.banished_unhide": "Show again",
        "accounts.banished_unknown": "Unknown calendar",

        // CalDAV add sheet
        "caldav.section": "Account details",
        "caldav.display_name": "Display name",
        "caldav.url": "CalDAV URL",
        "caldav.username": "Username",
        "caldav.password": "Password",
        "caldav.color": "Color",
        "caldav.color_label": "Color",
        "caldav.color_section": "Color",
        "caldav.connect": "Connect",
        "caldav.title": "CalDAV account",

        // Local cal add sheet
        "local.title": "Local calendar",
        "local.name": "Name",
        "local.color": "Color",
        "local.create": "Create",

        // Birthdays
        "birthday.new": "New birthday",
        "birthday.calendar_name": "Birthdays",
        "birthday.activate": "Enable birthday calendar",
        "birthday.activate_hint": "Enable the birthday calendar to add birthdays. It appears as its own calendar in the sidebar.",
        "birthday.person": "Name",
        "birthday.person_placeholder": "Person's name",
        "birthday.date": "Birthday",
        "birthday.year_unknown": "Year unknown",
        "birthday.no_calendars": "No birthday calendar yet. Create one first under “Accounts & Calendars”.",
        "birthday.is_calendar": "Birthday calendar",
        "birthday.is_calendar.desc": "All-day, yearly events with age and a birthday icon.",
        "birthday.notify": "Reminder",
        "birthday.notify.off": "Off",
        "birthday.notify.same_day": "On the day",
        "birthday.notify.one_day": "1 day before",
        "birthday.notify.days": "%d days before",
        "birthday.contacts.header": "Birthdays from Contacts",
        "birthday.contacts.sync": "Sync from Contacts",
        "birthday.contacts.target": "Target calendar",
        "birthday.contacts.sync_now": "Sync now",
        "birthday.contacts.synced": "Birthdays synced",
        "birthday.contacts.hint": "Copies birthdays from your contacts into the chosen birthday calendar – visible on all devices.",
        "birthday.contacts.denied": "No access to Contacts. Please allow it in iOS Settings.",
        "birthday.contacts.need_calendar": "Create a birthday calendar first.",

        // iCal add sheet
        "ical.title": "Subscribe to iCal",
        "ical.subscription": "Subscription",
        "ical.name": "Name",
        "ical.url": "iCal URL",
        "ical.color": "Color",
        "ical.refresh_section": "Refresh",
        "ical.interval": "Interval",
        "ical.subscribe": "Subscribe",
        "ical.refresh.15m": "Every 15 min",
        "ical.refresh.30m": "Every 30 min",
        "ical.refresh.1h": "Hourly",
        "ical.refresh.6h": "Every 6 hours",
        "ical.refresh.1d": "Daily",

        // HA add sheet
        "ha.section": "Home Assistant",
        "ha.display_name": "Display name",
        "ha.url_placeholder": "URL (e.g. http://homeassistant.local:8123)",
        "ha.auth_section": "Authentication",
        "ha.token": "Long-Lived Access Token",
        "ha.token_hint": "Create a token under: Profile → Security → Long-Lived Access Tokens",
        "ha.connect": "Connect"
    ]
]
